apiVersion: v1
kind: Service
metadata:
  name: moose-admission-webhook
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: moose-admission-webhook
subsets:
  - addresses:
      - ip: ${ENDPOINT}
    ports:
      - port: 8443
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "moose-admission-webhook"
webhooks:
- name: "mooses.animals.com"
  rules:
  - apiGroups:   ["animals.com"]
    apiVersions: ["v1"]
    operations:  ["*"]
    resources:   ["mooses"]
    scope:       "Namespaced"
  clientConfig:
    caBundle: ${CA_BUNDLE}
    service:
      namespace: "default"
      name: "moose-admission-webhook"  
      path: /
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 10
